site:
  title: Dev How To
  start_page: command-line-shell-script::index.adoc
content:
  sources:
  - url: https://gitlab.com/devhowto/command-line-shell-script
    branches: HEAD
    start_path: docs
  - url: https://gitlab.com/devhowto/algorithms-and-data-structure
    branches: HEAD
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
